# Site settings
title: SwiftierSwift | Swift3 Extended Libraries
tag_text: ![Swiftier](//raw.githubusercontent.com/omaralbeik/SwiftierSwift/master/logo.png)
description: page desc goes here

# Build settings
markdown: kramdown
exclude: ["readme.md"]
sass:
  style: compressed
